# Generated by Django 6.0.1 on 2026-02-08 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='cep',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='service_type',
            field=models.CharField(default='Indefinido', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='street',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.CreateModel(
            name='ServiceRequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='service_requests/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.servicerequest')),
            ],
        ),
    ]
