# Generated by Django 6.0.1 on 2026-02-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_servicerequest_cep_servicerequest_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='os_number',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, unique=True, verbose_name='Número da OS'),
        ),
    ]
