# Generated by Django 6.0.1 on 2026-02-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_servicerequest_os_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='os_number',
            field=models.CharField(db_index=True, editable=False, max_length=20, unique=True, verbose_name='Número da OS'),
        ),
    ]
