# Generated by Django 6.0.1 on 2026-02-10 20:09

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_servicerequest_os_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequestattachment',
            name='file',
            field=models.FileField(upload_to=core.models.attachment_upload_to, validators=[core.models.validate_image_type]),
        ),
    ]
