# Generated by Django 6.0.1 on 2026-02-26 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'permissions': [('tab_dashboard', 'Pode visualizar a aba Dashboard'), ('tab_users', 'Pode visualizar a aba Usuários'), ('tab_requests', 'Pode visualizar a aba Solicitações'), ('tab_os', 'Pode visualizar a aba Ordens de Serviço'), ('tab_reports', 'Pode visualizar a aba Relatórios'), ('manage_users', 'Pode gerenciar usuários (editar níveis/perfis)'), ('manage_os', 'Pode gerenciar OS (criar/editar)'), ('assign_os', 'Pode atribuir OS para responsáveis'), ('change_os_status', 'Pode alterar status da OS')]},
        ),
    ]
