# Generated by Django 6.0.1 on 2026-03-04 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_servicerequest_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'permissions': [('tab_dashboard', 'Pode visualizar a aba Dashboard'), ('tab_users', 'Pode visualizar a aba Usuários'), ('tab_requests', 'Pode visualizar a aba Solicitações'), ('tab_os', 'Pode visualizar a aba Ordens de Serviço'), ('tab_reports', 'Pode visualizar a aba Relatórios'), ('tab_team', 'Pode visualizar a aba Equipe'), ('manage_users', 'Pode gerenciar usuários (editar níveis/perfis)'), ('manage_os', 'Pode gerenciar OS (criar/editar)'), ('assign_os', 'Pode atribuir OS para responsáveis'), ('change_os_status', 'Pode alterar status da OS'), ('manage_team', 'Pode gerenciar Equipes (criar/editar/remover)')]},
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('function_description', models.TextField(blank=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Baixa'), ('MEDIUM', 'Média'), ('HIGH', 'Alta'), ('URGENT', 'Urgente')], default='MEDIUM', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams_responsible', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('team', 'user')},
            },
        ),
    ]
