# Generated by Django 6.0.1 on 2026-03-04 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_servicerequest_options_team_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='core.team', verbose_name='Equipe'),
        ),
    ]
