# Generated by Django 6.0.1 on 2026-03-09 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_servicerequest_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Prazo'),
        ),
    ]
