# Generated by Django 6.0.1 on 2026-03-25 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_servicetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='finished_in_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Finalizado em quantos dias'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='solution_taken',
            field=models.TextField(blank=True, null=True, verbose_name='Solução tomada'),
        ),
    ]
