# Generated by Django 6.0.1 on 2026-03-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_userprofile_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lgpd_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lgpd_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
