# Generated by Django 6.0.1 on 2026-04-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_userprofile_lgpd_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Pendente'), ('IN_PROGRESS', 'Em andamento'), ('DONE', 'Concluído')], default='OPEN', max_length=15),
        ),
    ]
