# Generated by Django 6.0.1 on 2026-06-06 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_servicerequest_status_updated_at_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='service_type_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests_ref', to='core.servicetype', verbose_name='Tipo de serviço'),
        ),
    ]
