# Generated by Django 6.0.1 on 2026-06-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_notificationhidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cargo_funcao',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Cargo / Função'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='setor',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Setor'),
        ),
    ]
