# Generated by Django 6.0.1 on 2026-06-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_userprofile_cargo_funcao_userprofile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='prazo_dias',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Prazo em dias'),
        ),
    ]
