# Generated by Django 6.0.1 on 2026-08-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_servicerequest_latitude_servicerequest_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de conclusão'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Início do andamento'),
        ),
    ]
